[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.mypy]
# `req_compile.private` deliberately has no `__init__.py` so that `setup.py`'s
# `find_packages` leaves the Bazel rule helpers out of the distribution.
namespace_packages = true

[tool.pylint.main]
max-line-length = 120
disable = [
    "fixme",  # Developers should be allowed to leave TODO comments as long as they're tracked by another issue
]

[tool.pylint."messages control"]
disable = [
    "R",
    "missing-docstring",
    "too-few-public-methods",
    "too-many-arguments",
    "raise-missing-from",
    "consider-using-f-string",
    "useless-import-alias",  # Conflict with ruff check.
]
