"""An example of building Python zipapps for platforms other than the host."""

module(
    name = "req_compile_example_cross_platform",
    version = "0.0.0",
)

bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.4")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "rules_venv", version = "0.26.0")
bazel_dep(name = "rules_req_compile", version = "0.0.0")
local_path_override(
    module_name = "rules_req_compile",
    path = "../..",
)

requirements = use_extension("@rules_req_compile//extensions:python.bzl", "requirements")
requirements.parse(
    name = "pip_deps",
    requirements_locks = {
        ":requirements.linux.txt": "@platforms//os:linux",
        ":requirements.macos.txt": "@platforms//os:macos",
        ":requirements.windows.txt": "@platforms//os:windows",
    },
)
use_repo(requirements, "pip_deps")

# Cross-platform builds require hermetic interpreters for each target platform.
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    # Working around a rules_python issue with docker
    # https://github.com/bazelbuild/rules_python/pull/713
    ignore_root_user_error = True,
    is_default = True,
    python_version = "3.11",
)
