"""An example of consuming a single platform requirements lock file."""

module(
    name = "req_compile_example_simple",
    version = "0.0.0",
)

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_venv", version = "0.26.0")
bazel_dep(name = "rules_req_compile", version = "0.0.0")
local_path_override(
    module_name = "rules_req_compile",
    path = "../..",
)

requirements = use_extension("@rules_req_compile//extensions:python.bzl", "requirements")
requirements.parse(
    name = "pip_deps",
    requirements_lock = ":requirements.txt",
)
use_repo(requirements, "pip_deps")
