"""An example of resolving requirements from a local `--find-links` directory."""

module(
    name = "req_compile_example_find_links",
    version = "0.0.0",
)

bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "rules_venv", version = "0.26.0")
bazel_dep(name = "rules_req_compile", version = "0.0.0")
local_path_override(
    module_name = "rules_req_compile",
    path = "../..",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    # Working around a rules_python issue with docker
    # https://github.com/bazelbuild/rules_python/pull/713
    ignore_root_user_error = True,
    is_default = True,
    python_version = "3.11",
)
use_repo(
    python,
    "python_3_11_aarch64-apple-darwin",
    "python_3_11_aarch64-unknown-linux-gnu",
    "python_3_11_x86_64-apple-darwin",
    "python_3_11_x86_64-pc-windows-msvc",
    "python_3_11_x86_64-unknown-linux-gnu",
)

# A source distribution is built so the test has a locally produced wheel
# to resolve out of a `--find-links` directory.
sdist_requirements = use_extension("@rules_req_compile//extensions:python.bzl", "requirements")
sdist_requirements.parse(
    name = "sdist_deps",
    interpreter_linux_aarch64 = "@python_3_11_aarch64-unknown-linux-gnu//:python",
    interpreter_linux_x86_64 = "@python_3_11_x86_64-unknown-linux-gnu//:python",
    interpreter_macos_aarch64 = "@python_3_11_aarch64-apple-darwin//:python",
    interpreter_macos_x86_64 = "@python_3_11_x86_64-apple-darwin//:python",
    interpreter_windows = "@python_3_11_x86_64-pc-windows-msvc//:python",
    requirements_lock = ":sdist_requirements.txt",
)
use_repo(
    sdist_requirements,
    "sdist_deps",
    "sdist_deps__pyspark",
)

find_links_test_repository = use_repo_rule("//:find_links_test_repo.bzl", "find_links_test_repository")

find_links_test_repository(
    name = "find_links_test",
    build_file = ":BUILD.find_links.bazel",
    pyspark_wheel_data = "@sdist_deps__pyspark//:whl.json",
    requirements_in = ":requirements.in",
    requirements_txt = ":requirements.txt",
    # Needs to match `--find-links` in `//:requirements.in`
    wheeldir = "wheeldir",
)

# Use a separate extension since @find_links_test is generated by an extension
# that also depends upon `@rules_req_compile//extensions:python.bzl`.
find_links_requirements = use_extension("//:extension.bzl", "requirements")
find_links_requirements.parse(
    name = "pip_deps",
    requirements_lock = "@find_links_test//:requirements.txt",
)
use_repo(find_links_requirements, "pip_deps")
