---
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: compile_requirements

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'The py_reqs_compiler target to run'
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-13", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Compile requirements
      run: |
        bazel run "${{ github.event.inputs.target }}" "--" "--upgrade" "--verbose"
